name: context variable

on:
  push:

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
    - name: uses of variable
      env:
        my_first: ${{ vars.name }}
      run: |
        echo "my_first name is ${{ env.my_first }}
