name: context variable

on:
  push:
env:
  my_first: ${{vars.name}}
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
    - name: uses of env
      run: |
        echo "my_first name is ${{ env.my_first }}
